Work done.
AvrumiG/Therapy-clinic pull request #1
Opened 2024-11-05 21:33 UTC by astrohlicpu

Hi,
Your scenario was really nicely made and included some challenges!
Please look over my work and let me know if you want any changes.

2024-12-08 19:11 UTC, AvrumiG requested changes
I went through your work, and it was very nicely done.
I found a few minor things to look at in the tables file and left you some comments.

P.S. Apologies for the late response—I took a break from the course last month due to moving.

2024-12-08 19:11 UTC, AvrumiG commented on TherapyClinicDB/1 Tables.sql
> +    DOB date not null constraint ck_ClientRecord_DOB_needs_to_be_more_then_8_years_old check(datediff(year,DOB,getdate()) >=8 ),
The date check constraint doesn't ensure that the client was 8yr old at the begining of the therapy, rather that he is older then 8 as of the current date.

2024-12-08 19:11 UTC, AvrumiG commented on TherapyClinicDB/1 Tables.sql
> +    TherapyReason varchar(35) not null constraint ck_ClientRecord_TherapyReason_cannot_be_Borderline_Personality_Disorder_or_Schizophrenia check(TherapyReason not in ('Schizophrenia','Borderline Pers
You haven't blocked blanks in the TherapyReason field. 
(Although the spec didn't clearly state that a value is mandatory, I would assume that it is)

2024-12-08 19:11 UTC, AvrumiG commented on TherapyClinicDB/1 Tables.sql
> +                        when 5 then 'Very improved' end ,
You haven't added `persisted` at the end of the computation, which is recommended as per Mr. Galis

2024-12-08 23:10 UTC, astrohlicpu commented on TherapyClinicDB/1 Tables.sql
> +    DOB date not null constraint ck_ClientRecord_DOB_needs_to_be_more_then_8_years_old check(datediff(year,DOB,getdate()) >=8 ),
Corrected. Moved constraint to end of table.

2024-12-08 23:12 UTC, astrohlicpu commented on TherapyClinicDB/1 Tables.sql
> +    TherapyReason varchar(35) not null constraint ck_ClientRecord_TherapyReason_cannot_be_Borderline_Personality_Disorder_or_Schizophrenia check(TherapyReason not in ('Schizophrenia','Borderline Pers
Fixed

2024-12-08 23:12 UTC, astrohlicpu commented on TherapyClinicDB/1 Tables.sql
> +                        when 5 then 'Very improved' end ,
My mistake. Fixed.

2024-12-08 23:13 UTC, astrohlicpu commented
Updated work to reflect all comments. Let me know if anything else is needed.

2024-12-26 20:20 UTC, AvrumiG commented
All good now, great job.

2024-12-26 20:20 UTC, closed without merging

2024-12-26 20:21 UTC, AvrumiG reviewed
All good now, reat job.